name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'To home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      enviroment:
        description: 'Enviroment to run test against'
        type: enviroment
        required: true
    
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in th repository
        run: |
          echo "The repository ${{github.repository}} contains the following files"
          tree

      - run: |
          echo "Homedrive: ${{inputs.homedrive}}"
          echo "Log level: ${{inputs.logLevel}}"
          echo "Tag source: ${{inputs.tag}}"
          echo "Enviroment: ${{inputs.enviroment}}"
        name: Workflow Inputs
        if: ${{github.event_name == 'workflow_dispatch'}}


  
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [macos-latest, ubuntu-latest]
        node_version: [12, 14, 16]
  
    name: Job2
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}


  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: "echo Job: ${{ github.job }}"
