name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'To home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      enviroment:
        description: 'Enviroment to run test against'
        type: enviroment
        required: true
    
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in th repository
        run: |
          echo "The repository ${{github.repository}} contains the following files"
          tree

      - run: |
          echo "Homedrive: ${{inputs.homedrive}}"
          echo "Log level: ${{inputs.logLevel}}"
          echo "Tag source: ${{inputs.tag}}"
          echo "Enviroment ${{input.enviroment}}"
        name: Workflow Inputs
        if: ${{github.event_name == 'workflow_dispatch'}}
          
